#version: "3.2"
#services:
#  rabbitmq:
#    image: rabbitmq:3.12-management
#    container_name: rabbitmq
#    hostname: rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: user


      version: '3.9'
      services:
        zookeeper:
          image: confluentinc/cp-zookeeper:7.3.2
          container_name: zookeeper
          ports:
            - "2181:2181"
          environment:
            ZOOKEEPER_CLIENT_PORT: 2181

        kafka:
          image: confluentinc/cp-kafka:7.3.2
          container_name: kafka
          ports:
            - "9092:9092"
          depends_on:
            - zookeeper
          environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092,EXTERNAL://kafka:29092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_JMX_PORT: 9997
            KAFKA_JMX_HOSTNAME: kafka

        kafka-ui:
          container_name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - 8082:8080
          environment:
            DYNAMIC_CONFIG_ENABLED: true

        db-keycloak:
          image: postgres:alpine
          container_name: db-keycloak
          restart: unless-stopped
          environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
          ports:
            - "54327:5432"

        keycloak:
            image: bitnami/keycloak
            container_name: keycloak
            restart: unless-stopped
            environment:
              KEYCLOAK_ADMIN_USER: admin
              KEYCLOAK_ADMIN_PASSWORD: admin
              KEYCLOAK_DATABASE_HOST: db-keycloak
              KEYCLOAK_DATABASE_NAME: keycloak
              KEYCLOAK_DATABASE_USER: root
              KEYCLOAK_DATABASE_PASSWORD: root
              KEYCLOAK_EXTRA_ARGS: --import-realm
            ports:
              - "9080:8080"
            depends_on:
              - db-keycloak


