#version: "3.2"
#services:
#  rabbitmq:
#    image: rabbitmq:3.12-management
#    container_name: rabbitmq
#    hostname: rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: user


      version: '3.9'
      services:
        zookeeper:
          image: confluentinc/cp-zookeeper:7.3.2
          container_name: zookeeper
          ports:
            - "2181:2181"
          environment:
            ZOOKEEPER_CLIENT_PORT: 2181

        kafka:
          image: confluentinc/cp-kafka:7.3.2
          container_name: kafka
          ports:
            - "9092:9092"
          depends_on:
            - zookeeper
          environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092,EXTERNAL://kafka:29092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_JMX_PORT: 9997
            KAFKA_JMX_HOSTNAME: kafka

        kafka-ui:
          container_name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - 8082:8080
          environment:
            DYNAMIC_CONFIG_ENABLED: true



